### ISSUE TITLE
SDL2 build fails on KUbuntu 25.10

### ISSUE THREAD

**Issue by Blad3forc3** [joncampbell123/dosbox-x#6037]
### Describe the bug

Build fails on Kubuntu 25.10

### Steps to reproduce the behaviour

1.Download source
2.Run build-debug-sdl2

### Expected behavior

Build compiles

### What operating system(s) this bug have occurred on?

Kubuntu 25.10

### What version(s) of DOSBox-X have this bug?

Latest source as of 4/1/2026

### Used configuration

```ini
N.A
```

### Output log

```text
In file included from /usr/include/SDL2/SDL.h:49,
                 from /usr/include/SDL2/SDL_net.h:40,
                 from misc_util.h:66,
                 from softmodem.h:28,
                 from serialport.cpp:38:
/usr/include/SDL2/SDL_log.h:355:100: error: expected initializer before ‘SDL_PRINTF_VARARG_FUNCV’
  355 |                                              SDL_PRINTF_FORMAT_STRING const char *fmt, va_list ap) SDL_PRINTF_VARARG_FUNCV(3);
      |                                                                                                    ^~~~~~~~~~~~~~~~~~~~~~~
make[4]: *** [Makefile:389: serialport.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/media/ade/Temp/Build/dosbox-x/src/hardware/serialport'
make[3]: *** [Makefile:855: all-recursive] Error 1
make[3]: Leaving directory '/media/ade/Temp/Build/dosbox-x/src/hardware'
make[2]: *** [Makefile:552: all-recursive] Error 1
make[2]: Leaving directory '/media/ade/Temp/Build/dosbox-x/src'
make[1]: *** [Makefile:413: all-recursive] Error 1
make[1]: Leaving directory '/media/ade/Temp/Build/dosbox-x'
make: *** [Makefile:346: all] Error 2
```

### Have you checked that no similar bug report(s) exist?

- [x] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [x] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
/usr/include/SDL2/SDL_log.h is not a part of DOSBox-X code tree, so this should be reported to SDL2 developers.
Current code uses the headers from the package installed.
Also, check your SDL2 version, since the nightly builds using 2.30.0 in github (Ubuntu 24.04) are built successfully.

Edit: According to the log, the library used in the recent nightly builds are as below.
> Setting up libsdl2-dev:amd64 (2.30.0+dfsg-1ubuntu3.1) ...

**Comment by maron2000** [comment]
Or you can try building the in-tree SDL2 code, by deleting the `if test` and the corresponding `fi` in the build script.
Again, this is usually NOT required for Linux.

```sh
# prefer to compile against our own copy of SDL 2.x IF the system does not provide one
if [[ "$no_host_sdl2" ]]; then
    x="" # doesn't work well cross-compiling
else
    x="$(which sdl2-config)"
fi
if test -z "${x}" ; then
    echo "Compiling our internal SDL 2.x"
    (cd vs/sdl2 && ./build-dosbox.sh) || exit 1
fi
```

**Comment by cmitu** [comment]
@Blad3forc3 are you using `gcc` to compile or `clang` ? The `SDL_PRINTF_VARARG_FUNC` macro is defined (in SDL2) only for `gcc`.

**Comment by Blad3forc3** [comment]
I am using GCC. I have managed to get it to compile by manually compiling sdl2 as maron2000 said

**Comment by maron2000** [comment]
pleas close solved issues,.
