### ISSUE TITLE
macOS compile error in ne2000.cpp

### ISSUE THREAD

**Issue by martinlindhe** [joncampbell123/dosbox-x#441]
After resolving #439, another compile issue on macOS:

```
In file included from ne2000.cpp:54:
In file included from /usr/include/pcap.h:43:
/usr/include/pcap/pcap.h:544:12: fatal error: 'remote-ext.h' file not found
  #include <remote-ext.h>
```

I have previously fixed this issue in https://github.com/joncampbell123/dosbox-x/commit/45ce0bf37b477d91faf9f80ed4abb1192f033647, but it was reintroduced in 14bce91b
