### ISSUE TITLE
Error in vga_draw.cpp when building from source on Debian

### ISSUE THREAD

**Issue by Spessmen14** [joncampbell123/dosbox-x#6415]
### Describe the bug

vga_draw.cpp:5927:70: error: ‘png_const_bytep’ was not declared in this scope; did you mean ‘png_const_charp’?

After some research I found this may be related to an outdated libpng library but I checked mine and it shows 1.6:

$ dpkg -l | grep libpng-dev 
ii  libpng-dev:arm64                     1.6.48-1+deb13u5                     arm64        PNG library - development (version 1.6)

### Steps to reproduce the behaviour

Follow "general procedures" under 

https://github.com/joncampbell123/dosbox-x/blob/master/BUILD.md

First install the required tools and libraries, such as git, gcc, g++, make, Autotools, pkg-config, nasm, libxkbfile. Depending on the [options](https://github.com/joncampbell123/dosbox-x/blob/master/BUILD.md#libraries-used-by-dosbox-x) you want, some more may be required.
    Download the source code from the github repository

git clone https://github.com/joncampbell123/dosbox-x.git
cd dosbox-x

    General Linux or BSD compile (SDL1)

./build-debug
sudo make install

### Expected behavior

Dosbox-X should build 

### What operating system(s) this bug have occurred on?

Debian Trixie ARM64

### What version(s) of DOSBox-X have this bug?

current github source

### Used configuration

```ini

```

### Output log

```text
vga_draw.cpp: In function ‘void WriteARawImage(rawscreenshot&, rawscreenshot&, const char*)’:
vga_draw.cpp:5927:70: error: ‘png_const_bytep’ was not declared in this scope; did you mean ‘png_const_charp’?
 5927 |         if (rawpal.image_palette2 != NULL) png_write_chunk(png_ptr, (png_const_bytep)("rPAL"), rawpal.image_palette2, rawpal.image_palette2_size*3);
      |                                                                      ^~~~~~~~~~~~~~~
      |                                                                      png_const_charp
make[4]: *** [Makefile:840: vga_draw.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/flux/dosbox-x/src/hardware'
make[3]: *** [Makefile:862: all-recursive] Error 1
make[3]: Leaving directory '/home/flux/dosbox-x/src/hardware'
make[2]: *** [Makefile:560: all-recursive] Error 1
make[2]: Leaving directory '/home/flux/dosbox-x/src'
make[1]: *** [Makefile:417: all-recursive] Error 1
make[1]: Leaving directory '/home/flux/dosbox-x'
make: *** [Makefile:350: all] Error 2
```

### Have you checked that no similar bug report(s) exist?

- [x] I have searched and didn't find any similar bug report.

### Code of Conduct & Contributing Guidelines

- [x] I agree to follow the code of conduct and the contributing guidelines.

**Comment by maron2000** [comment]
`png_const_bytep` is obviously included in the latest libpng16 (1.6.59),  so if it's not in Debian, you should report that to the Debian package builders.
I don't know why they removed that.

https://github.com/pnggroup/libpng/blob/libpng16/pngconf.h

Edit: The nightly builds on Ubuntu uses 1.6.43 which is older than yours, so your 1.6.48 should include that as well.

**Comment by Spessmen14** [comment]
This version of Debian was built for a Termux Proot environment, so things
are often a but different and/or not quite right. I'll try and get in touch
with them.

**Comment by maron2000** [comment]
There's nothing that can be done on DOSBox-X, so please close this issue.
