### ISSUE TITLE
Unable to compile in MacOS 10.13

### ISSUE THREAD

**Issue by josephillips85** [joncampbell123/dosbox-x#1643]
Trying to compile dosbox-x for new functionatily

when im compiling dosbox im getting a error in this line

dosbox.cpp:4039:18: error: variable has incomplete type 'struct utimbuf'
  struct utimbuf ut;

Ideas?

**Comment by josephillips85** [comment]
issue happened too in mac os 10.15

**Comment by joncampbell123** [comment]
Does Mac OS X have the utimes() function?

**Comment by josephillips85** [comment]
Hi Joncampbell 
i already fix it is a missing line on top of the file i will commit a fix after i solve a issue with a opl2board.
