### ISSUE TITLE
Doesn't build on arm64 FreeBSD 13.0-RELEASE

### ISSUE THREAD

**Issue by clausecker** [joncampbell123/dosbox-x#2605]
**Describe the bug**
I am trying to add a port for dosbox-x to the ports tree.  Besides some minor issues (poorly documented dependencies, some minor patches needed for `include/byteorder.h`), there is one major issue preventing the build right now:

The code does not build on arm64 FreeBSD 13.0-RELEASE due to dosbox-x assuming `long double` is an 80 bit type and supports x86-like `_FPU_SETCW` calls.

Here's what the errors look like:

```
In file included from core_dynrec.cpp:173:
In file included from ./core_dynrec/decoder.h:25:
In file included from ./core_dynrec/dyn_fpu.h:52:
./core_dynrec/../../fpu/fpu_instructions_longdouble.h:29:12: fatal error: 'fpu_control.h' file not found
#  include <fpu_control.h>
           ^~~~~~~~~~~~~~~
```

The byte order issue is patched by applying NetBSD behaviour to FreeBSD, too:

```
--- include/byteorder.h.orig	2021-06-19 13:37:28 UTC
+++ include/byteorder.h
@@ -115,11 +115,11 @@
 #define _BSD_SOURCE
 #include <endian.h>
 
-#elif defined(__NetBSD__) || defined(__OpenBSD__)
+#elif defined(__NetBSD__) || defined(__OpenBSD__) || defined(__FreeBSD__)
 
 #include <sys/endian.h>
 
-#elif defined(__FreeBSD__) || defined(__DragonFly__)
+#elif defined(__DragonFly__)
 
 #include <sys/endian.h>
```

**To Reproduce**
Build dosbox-x on arm64 FreeBSD 13.0-RELEASE (I built with sdl2, but I don't think this makes a difference).

**Expected behavior**
A successful build.

**Environment (please complete the following information):**
 - Operating system: FreeBSD 13.0-RELEASE on arm64
 - dosbox-x-v0.83.14

**Comment by Wengier** [comment]
I don't have a FreeBSD environment to test myself. If you know how to fix the error(s) to make it build successfully on your FreeBSD platform, please feel free to send pull request to fix the issue. Thanks for your support.

P.S. There is now a dedicated [BUILD.md](https://github.com/joncampbell123/dosbox-x/blob/master/BUILD.md) page for building the DOSBox-X source code. If the source code can be built successfully on FreeBSD then such information may be added on the page as well.

**Comment by clausecker** [comment]
If it helps I could give you temporary access to a FreeBSD box.  Alternatively, I could try and debug this myself, but I am not too familiar with the details of this project, so I'm not sure if it'll work out.  I recall that previous versions of Dosbox-X did build, so perhaps some change in the meanwhile broke it.  Let me see if I can bisect this.

**Comment by Wengier** [comment]
@clausecker I am not really familiar with FreeBSD myself, but you can certainly try to make some change to make it build successfully there. Thanks for your support.

**Comment by Slesa** [comment]
I've made a PR which compiles on a GhostBSD which reports itself as a FreeBSD 13.0 Stable - but it does not run as expected. I would be interested to create a port if somebody could help me. And get it stable of course

**Comment by clausecker** [comment]
Hi, this sounds great!  Can you link the PR so I can have a look?  Let's make this a group effort.

**Comment by Slesa** [comment]
https://github.com/joncampbell123/dosbox-x/pull/2911
