### ISSUE TITLE
dosbox-x.exe mygame.exe doesn't start mygame

### ISSUE THREAD

**Issue by cawoodm** [joncampbell123/dosbox-x#864]
The following command should launch DOSBOX-X with a game but it just launches DOSBOX-X to the Z:\> Console:
```
C:\Marc\Games\DOS\DOSBOXX\dosbox-x.exe "C:\Marc\Games\DOS\colonization\viceroy.exe" -noconsole -fullscreen
```
The above command works fine with the normal DOSBOX.

If I start DOSBOX I am able to mount and run the game.

Windows 10 64bit.

DOSBox version DOSBox-X, copyright 2002-2015 DOSBox Team.

![image](https://user-images.githubusercontent.com/498834/44108665-640bd1ac-9ffb-11e8-9a73-f2343efedba4.png)

**Comment by ThePillenwerfer** [comment]
Still doesn't work on the latest version (0.82.11).

**Comment by joncampbell123** [comment]
If you can compile from source, pull the latest commit and try again.

**Comment by joncampbell123** [comment]
Please try the latest commit. I will close this issue if you do not respond by December 1st.

**Comment by joncampbell123** [comment]
Got it. I'll compile a quick beta and put it in releases.

You can compile the source in Linux using the ./build-debug script and you can use Visual Studio 2017 Community Edition to compile in Windows, if you are willing to try.

**Comment by ThePillenwerfer** [comment]
The dosbox-x-windows-20181121-224144-windows version works fine so thanks for that.

As for building myself, Visual Studio 2017 is a non-starter as the latest Windows I have is Vista and it won't run under that.

I've tried again on Linux Mint 17.1 32-Bit Mate Edition and for all that ./autogen and ./configure seemed to work fine build failed with this error:—
[code]
sdlmain_linux.cpp:13:37: fatal error: X11/extensions/XKBrules.h: No such file or directory
 #include <X11/extensions/XKBrules.h>
                                     ^
compilation terminated.
make[3]: *** [sdlmain_linux.o] Error 1
make[3]: Leaving directory `/home/joe/dosbox-x-dosbox-x-v0.82.11/src/gui'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/joe/dosbox-x-dosbox-x-v0.82.11/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/joe/dosbox-x-dosbox-x-v0.82.11'
make: *** [all] Error 2
[/code]

**Comment by joncampbell123** [comment]
Most Linux distributions like to ship the binaries for packages without the development headers. I'm not familiar with the package tool in Mint but usually the development headers are included with the package with -dev at the end.
