### ISSUE TITLE
[git]Build process stops in debug_gui.cpp:259:14: when using ncurses 6.3.

### ISSUE THREAD

**Issue by FredBezies** [joncampbell123/dosbox-x#3039]
### Code of Conduct & Contributing Guidelines

- [X] I agree to follow the code of conduct and the contributing guidelines.

### Have you checked that no other similar bug report(s) already exists?

- [X] I have searched and didn't find any similar issues.

### What operating system(s) this bug have occurred on?

Archlinux

### What version(s) of DOSBox-X have this bug?

commit 2da592e

### Describe the bug

Hello.

I was trying to get a build of dosbox-x based on commit 2da592e but it breaks in debug_gui.cpp:259:14:

Here is the error log:

```
debug_gui.cpp: In function ‘void DBGUI_DrawDebugOutputLine(int, std::string)’:
debug_gui.cpp:259:14: error: format not a string literal and no format arguments [-Werror=format-security]
  259 |     mvwprintw(dbg.win_out, y, 0, const_cast<char*>(line.c_str()));
      |     ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
cc1plus: some warnings being treated as errors
make[3]: *** [Makefile:363: debug_gui.o] Error 1
```

### Expected behavior

Build process going on.

### Steps to reproduce the behaviour

1. grab commit 2da592e
2. use these configure options: ./configure --enable-core-inline --enable-debug --enable-avcodec --prefix=/usr --enable-sdl2
3. wait

I'm using gcc 11.1.0 on an up-to-date archlinux.

**Comment by maron2000** [comment]
Just for your reference, I successfully built on Ubuntu 18.04 + gcc 7.5.0 (default compiler)
```
./configure --enable-core-inline --enable-debug --enable-avcodec --prefix=/usr --enable-sdl2
make -j3
```

**Comment by FredBezies** [comment]
Just for your information - besides using a prehistoric version of gcc :) - my last working homemade build was based on commit 07d9a19abb

Well, I'll do a little git "dissecting" to find the breaking commit.

**Comment by FredBezies** [comment]
Found the breakin commit: df72c06

Here is the error log I got:

```
debug_gui.cpp: In function ‘void DBGUI_DrawDebugOutputLine(int, std::string)’:
debug_gui.cpp:259:14: error: format not a string literal and no format arguments [-Werror=format-security]
  259 |     mvwprintw(dbg.win_out, y, 0, const_cast<char*>(line.c_str()));
      |     ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-int-to-void-pointer-cast’ may have been intended to silence earlier diagnostics
cc1plus: some warnings being treated as errors
make[3]: *** [Makefile:363: debug_gui.o] Error 1
```

**Comment by maron2000** [comment]
> besides using a prehistoric version of gcc :)
So nice of you to point out such information, for a default compiler of a certain OS.

**Comment by FredBezies** [comment]
> > besides using a prehistoric version of gcc :)
> > So nice of you to point out such information, for a default compiler of a certain OS.

It was only humour. Sorry if I hurt you. But gcc 7.5.xx is long dead for gcc developers.

Oldest version support as of November 9th, 2021 is gcc 8.5 -> https://gcc.gnu.org/gcc-8/

**Comment by maron2000** [comment]
Yeah, I know that. 
That's why I emphasized in my previous comment that 7.5.0 is the _default_ compiler,
and my intension was to show the fact that there are no problem in certain environments.

**Comment by grapeli** [comment]
@FredBezies 
I cannot confirm this under Archlinux.

Both using the distribution version of **gcc 11.1.0** and others in versions 11.1.1 and 9.3.1. In any case, the build process is successful.
Please provide more details. Do you use any specific compiler flags?

**Comment by FredBezies** [comment]
> @FredBezies I cannot confirm this under Archlinux.
> 
> Both using the distribution version of **gcc 11.1.0** and others in versions 11.1.1 and 9.3.1. In any case, the build process is successful. Please provide more details. Do you use any specific compiler flags?

No specific compiler flags. I'm just using the ones from /etc/makepkg.conf:

```
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
 ```

Will try again, cleaning all building cache.

**Comment by FredBezies** [comment]
I forgot to post the FLAGS set up in /etc/makepkg.conf which are the same as the one in pacman 6.0.1-2.

```
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
```

**Comment by grapeli** [comment]
I suggest carrying out a verification first.
By doing the following.
```
git clone https://github.com/joncampbell123/dosbox-x
cd dosbox-x
./autogen.sh
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection" CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS" LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" ./configure --enable-core-inline --enable-debug --enable-avcodec --prefix=/usr --enable-sdl2
make -j$(nproc)
```
**The whole process is successful under Archlinux.**

If you have problems with makepkg, pacman, PKGBUILD, AUR under Archlinux, please contact them for help on forum, mailing list of your distribution.

**Comment by FredBezies** [comment]
> I suggest carrying out a verification first. By doing the following.
> 
> ```
> git clone https://github.com/joncampbell123/dosbox-x
> cd dosbox-x
> ./autogen.sh
> CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection" CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS" LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" ./configure --enable-core-inline --enable-debug --enable-avcodec --prefix=/usr --enable-sdl2
> make -j$(nproc)
> ```
> 
> **The whole process is successful under Archlinux.**
> 
> If you have problems with makepkg, pacman, PKGBUILD, AUR or any other mess on your system, please contact them for help on forum, mailing list of your distribution - Archlinux.

Quick answers.

1) No need to add CFLAGS line, it is in /etc/makepkg.conf -> https://github.com/archlinux/svntogit-packages/blob/packages/pacman/trunk/pacman.conf
2) I'm the maintainer on AUR of both dosbox-x-sdl and dosbox-x-sdl2-git
3) I do not understand why the PKGBUILD I used stop working in a few hours.
4) Will test the "simple git" verification and report.

**Comment by FredBezies** [comment]
Still broken.

Error log:

```
debug_gui.cpp: In function 'void DBGUI_DrawDebugOutputLine(int, std::string)':
debug_gui.cpp:259:14: error: format not a string literal and no format arguments [-Werror=format-security]
  259 |     mvwprintw(dbg.win_out, y, 0, const_cast<char*>(line.c_str()));
      |     ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: note: unrecognized command-line option '-Wno-int-to-void-pointer-cast' may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option '-Wno-int-to-void-pointer-cast' may have been intended to silence earlier diagnostics
cc1plus: some warnings being treated as errors
make[3]: *** [Makefile:363: debug_gui.o] Error 1
make[3]: *** Waiting for unfinished jobs....
debug.cpp: In function 'void DrawRegisters()':
debug.cpp:1134:41: warning: format '%X' expects argument of type 'unsigned int', but argument 5 has type 'Bitu' {aka 'long unsigned int'} [-Wformat=]
 1134 |         mvwprintw (dbg.win_reg,2,72,"%01X",GETFLAG(IOPL)>>12);
      |                                      ~~~^
      |                                         |
      |                                         unsigned int
      |                                      %01lX
debug.cpp:1138:41: warning: format '%X' expects argument of type 'unsigned int', but argument 5 has type 'Bitu' {aka 'long unsigned int'} [-Wformat=]
 1138 |         mvwprintw (dbg.win_reg,2,78,"%01X",cpu.cpl);
      |                                      ~~~^  ~~~~~~~
      |                                         |      |
      |                                         |      Bitu {aka long unsigned int}
      |                                         unsigned int
      |                                      %01lX
debug.cpp:1154:44: error: format not a string literal and no format arguments [-Werror=format-security]
 1154 |                 mvwprintw(dbg.win_reg,2,28,out1);
      |                                            ^~~~
debug.cpp:1155:44: error: format not a string literal and no format arguments [-Werror=format-security]
 1155 |                 mvwprintw(dbg.win_reg,3,28,out2);
      |                                            ^~~~
debug.cpp:1159:38: warning: format '%u' expects argument of type 'unsigned int', but argument 5 has type 'Bitu' {aka 'long unsigned int'} [-Wformat=]
 1159 |         mvwprintw(dbg.win_reg,3,60,"%u       ",cycle_count);
      |                                     ~^         ~~~~~~~~~~~
      |                                      |         |
      |                                      |         Bitu {aka long unsigned int}
      |                                      unsigned int
      |                                     %lu
debug.cpp: In function 'void DEBUG_Enable_Handler(bool)':
debug.cpp:3613:39: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 3613 |     if (debugrunmode==1) ParseCommand("RUN");
      |                                       ^~~~~
debug.cpp:3614:44: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 3614 |     else if (debugrunmode==2) ParseCommand("RUNWATCH");
      |                                            ^~~~~~~~~~
debug.cpp: In function 'void DrawVariables()':
debug.cpp:4550:34: error: format not a string literal and no format arguments [-Werror=format-security]
 4550 |                         mvwprintw(dbg.win_var, (int)y,  (int)x, dv->GetName());
      |                         ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
debug.cpp:4551:91: error: format not a string literal and no format arguments [-Werror=format-security]
 4551 | printw(dbg.win_var, (int)y, ((int)x + DEBUG_VAR_BUF_LEN + 1) , buffer);
      |                                                                ^~~~~~

At global scope:
cc1plus: note: unrecognized command-line option '-Wno-int-to-void-pointer-cast' may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option '-Wno-int-to-void-pointer-cast' may have been intended to silence earlier diagnostics
cc1plus: some warnings being treated as errors
make[3]: *** [Makefile:363: debug.o] Error 1
make[2]: *** [Makefile:528: all-recursive] Error 1
make[1]: *** [Makefile:400: all-recursive] Error 1
make: *** [Makefile:333: all] Error 2
make -s -j4  94.93s user 1.48s system 255% cpu 37.805 total
```

**Comment by maron2000** [comment]
I think removing `-Werror=format-security` from the CFLAGS will enable build process.
However, it may not satisfy the security criteria to make AUR packages.
I don't know treating these warnings as errors is reasonable, though.

**Comment by FredBezies** [comment]
> I think removing `-Werror=format-security` from the CFLAGS will enable build process. However, it may not satisfy the security criteria to make AUR packages. I don't know treating these warnings as errors is reasonable, though.

An idea to test. By the way, same breakage on a cleanly installed VM.

See attached screenshot.
![Capture d’écran de 2021-11-05 11-32-04](https://user-images.githubusercontent.com/8571419/140497305-8a2b62b8-4c0c-4940-8f56-7fb88583f196.png)

**Comment by maron2000** [comment]
I tested on Ubuntu with gcc 11.1, and built successfully.
I think it is because `-Werror` option is not enabled by default as in yours.

**Comment by grapeli** [comment]
I have no problems with Archlinux as well.

https://user-images.githubusercontent.com/452325/140500199-55556fe0-bb63-4dbc-8ec4-bcbd64d1ed64.mp4

**Comment by FredBezies** [comment]
There's something I do not understand. Well, I worked around this issue by using --disable-debug option.

**Comment by grapeli** [comment]
Your PKBUILD contains redundant dependencies.
The library that is listed in dpends - `physfs` is not used in the configuration process, in the compilation process, nor in the linking process. It is redundant.
The URL has nothing to do with DOSBox-X.

I downloaded https://aur.archlinux.org/cgit/aur.git/snapshot/dosbox-x-sdl2-git.tar.gz.
I changed `--disable-debug` to **enable** in PKGBUILD.
I typed `makepg -r` in the terminal. As a result, I got a ready package for installation.

**Comment by FredBezies** [comment]
> Your PKBUILD contains redundant dependencies. The library that is listed in dpends - `physfs` is not used in the configuration process, in the compilation process, nor in the linking process. It is redundant. The URL has nothing to do with DOSBox-X.

Fixing URL, my bad! Thanks. 

Build the package (without debug option in order to get a package). And I build it in a clean chroot, so no interferences from my real system.

Using namcap on it, I got this output:

```
$ namcap dosbox-x-sdl2-git-1:0.83.19.r33.gf210e0d5c-1-x86_64.pkg.tar.zst 
dosbox-x-sdl2-git W: Dependency 'ncurses' on your system is a testing release
dosbox-x-sdl2-git W: Unused shared library '/usr/lib/libncursesw.so.6' by file ('usr/bin/dosbox-x')
dosbox-x-sdl2-git W: Unused shared library '/usr/lib/libglib-2.0.so.0' by file ('usr/bin/dosbox-x')
dosbox-x-sdl2-git W: Dependency included and not needed ('physfs')
```

Why physfs? Just for full live archive support introduced in dosbox-x 0.83.9 back in january 2021 - https://dosbox-x.com/release-0.83.9.html

```
Implemented PhysFS support so that you can mount archives (e.g. ZIP/7Z) as drives in read-only mode, e.g. "MOUNT C TEST.ZIP" or "MOUNT D FILES.7Z". Some code is ported from a custom DOSBox fork. The menu option "Mount an archive file (ZIP/7Z)" is added to Drive menu to mount archives as Drives. (Wengier) 
```

And before you say it is a bug related to testing usage, here are the package from testing on my computer as of november 5th, 2021:

```
clang 13.0.0-2
compiler-rt 13.0.0-1
gnupg 2.2.32-1
jre-openjdk 17.0.1.u12-1
jre-openjdk-headless 17.0.1.u12-1
libva-mesa-driver 21.2.5-1
linux 5.15.arch1-1
linux-headers 5.15.arch1-1
llvm 13.0.0-2
llvm-libs 13.0.0-2
mesa 21.2.5-1
ncurses 6.3-1
pinentry 1.2.0-1
postgresql-libs 13.4-2
python-numpy 1.21.3-1
python-pyopenssl 21.0.0-1
python-shiboken2 5.15.2-10
python2-pyopenssl 21.0.0-1
qt5-tools 5.15.2+kde+r17-4
soundtouch 2.3.0-2
vulkan-mesa-layers 21.2.5-1
vulkan-radeon 21.2.5-1
```

Besides mesa, I do not which testing package can break building process here. Or ncurses? I'll try downgrading ncurses to see if it is better.

> 
> I downloaded https://aur.archlinux.org/cgit/aur.git/snapshot/dosbox-x-sdl2-git.tar.gz. I changed `--disable-debug` to **enable** in PKGBUILD. I typed `makepg -r` in the terminal. As a result, I got a ready package for installation.

With makepkg -r, depends are not handled. But I could be wrong.

**Comment by FredBezies** [comment]
Dosbox-x code is NOT compatible with ncurses 6.3 when enabling debug. Modifying the bug title.

**Comment by grapeli** [comment]
[build.log](https://github.com/joncampbell123/dosbox-x/files/7486512/build.log)

**Comment by FredBezies** [comment]
> [build.log](https://github.com/joncampbell123/dosbox-x/files/7486512/build.log)

Downgrading ncurses to version 6.2 fixes the issue. Now, which code used with ncurses 6.3 leads to this bug?

**Comment by grapeli** [comment]
@FredBezies
Show me where your `physfs` library is used by dosbox-x.

**Comment by FredBezies** [comment]
> @FredBezies Show me where your `physfs` library is used by dosbox-x.

Just try to open an zip / 7z archive.

**Comment by grapeli** [comment]
@FredBezies 
After all, you pasted the result from the namcap post above.
```
$ namcap dosbox-x-sdl2-git-1:0.83.19.r33.gf210e0d5c-1-x86_64.pkg.tar.zst
dosbox-x-sdl2-git W: Dependency included and not needed ('physfs')
```

Physfs is bundled with dosbox-x sources.
https://github.com/joncampbell123/dosbox-x/tree/master/src/libs/physfs
This library is in the binary:
`nm -g dosbox-x | grep -i physfs`

**Comment by FredBezies** [comment]
> @FredBezies After all, you pasted the result from the namcap post above.
> 
> ```
> $ namcap dosbox-x-sdl2-git-1:0.83.19.r33.gf210e0d5c-1-x86_64.pkg.tar.zst
> dosbox-x-sdl2-git W: Dependency included and not needed ('physfs')
> ```
> 
> Physfs is bundled with dosbox-x sources. https://github.com/joncampbell123/dosbox-x/tree/master/src/libs/physfs This library is in the binary: `nm -g dosbox-x | grep -i physfs`

Just look at the last dosbox-x-sdl2-git PKGBUILD :)

**Comment by grapeli** [comment]
@FredBezies 
I have upgraded ncurses from the testing repository up to version 6.3.
In fact, the compilation error is mentioned with the default (restrictive) flags.

By omitting `-Werror=format-security` compilation works fine with ncurses 6.3.

**Comment by grapeli** [comment]
@FredBezies 
Instead of dropping the debug function, modify PKGBUILD by adding (temporarily):
```
CFLAGS=${CFLAGS/-Werror=format-security/}
CXXFLAGS=${CXXFLAGS/-Werror=format-security/}
```

**Comment by maron2000** [comment]
@grapeli
I agree with dropping `-Werror` option only.
I think ncurses should fix that it requires `const_cast`.

**Comment by grapeli** [comment]
@maron2000 
Certainly.
Or else `-Wno-format -Wno-format-security`.
Generally, abandoning `--enable-debug` is too far-fetched. I suspect that this is a feature that a group of users use often.

**Comment by FredBezies** [comment]
Updated both dosbox-x-sdl2 - https://aur.archlinux.org/cgit/aur.git/commit/?h=dosbox-x-sdl2&id=9c34e0020ee1b70eb41de9f1864b81434c9f3e1a - and dosbox-x-sdl2-git - https://aur.archlinux.org/cgit/aur.git/commit/?h=dosbox-x-sdl2-git&id=4857ae0bf14b74576d11ce9a55d76cac3a880b81 - to get a better workaround for this bug.

**Comment by grapeli** [comment]
@Wengier 
You could see if such a change is acceptable.
[format-security.patch.txt](https://github.com/joncampbell123/dosbox-x/files/7492085/format-security.patch.txt)

**Comment by rderooy** [comment]
fix was merged. I think this can be closed.

**Comment by FredBezies** [comment]
> fix was merged. I think this can be closed.

So let's close it :)
