### PR TITLE
Menu option to create blank disk images and solve issues #2078, #2081, #2082, #2083

### PR DESCRIPTION
**Pull request by Wengier**
@rderooy had previously suggested the ability to create blank disk images from menu in Issue #1988. So this adds a "Create blank disk image" menu option in "DOS" menu to create blank floppy or hard disk images of a common disk size, including 1.2MB,1.44MB, 2.88MB for floppy images as well as 250MB, 520MB, 1GB, 2GB, 4GB and 8GB for hard disk images.

Also solved the file system problem for Issue #2078, the time auto-synchronization ability for Issue #2081 and #2082, and custom LPT4-9 ports for Issue #2083.

### CODE REVIEW

**Comment by joncampbell123** [comment]
@Wengier Unrelated question: Two parts of DOSBox-X now no longer compile with GCC 4.8.5. One is the use of the PRIx64 defines in inttypes.h for some reason, the other is a call to std::istringstream::swap in render.cpp which GCC 4.8.5 does not recognize apparently, despite supporting C++11 otherwise.

Does anyone here still care to compile with GCC 4.8.5, or should the project just require a later version of GCC that provides both of those C++ features?

**Comment by joncampbell123** [comment]
render.cpp:965:24: error: ‘std::stringstream’ has no member named ‘swap’
             if (empty) buf.swap(tmp);

    whereami.c: In function ‘int wai_getModulePath(char*, int, int*)’:
    whereami.c:268:30: error: expected ‘)’ before ‘PRIx64’
           if (sscanf(buffer, "%" PRIx64 "-%" PRIx64 " %s %" PRIx64 " %x:%x %u %s\n", &low, &high, perms, &offset, &major, &minor, &inode, path) == 8)
    whereami.c:268:139: warning: spurious trailing ‘%’ in format [-Wformat=]
           if (sscanf(buffer, "%" PRIx64 "-%" PRIx64 " %s %" PRIx64 " %x:%x %u %s\n", &low, &high, perms, &offset, &major, &minor, &inode, path) == 8)
                                                                                                                                           ^

**Comment by Wengier** [comment]
@joncampbell123 I don't have GCC 4.8.5 for testing here, but if these are the only issues for compilation with GCC 4.8.5, I don't think they are very difficult to be fixed though.

**Comment by Wengier** [comment]
@joncampbell123 I hope the code in my new PR will fix the said issues with GCC 4.8.5. I don't have GCC 4.8.5 to verify myself though.

**Comment by joncampbell123** [comment]
@Wengier Nope. GCC 4.8.5 considers the constructor deleted.

render.cpp: In function ‘bool RENDER_GetShader(std::string&, char*)’:
render.cpp:922:23: error: use of deleted function ‘std::basic_stringstream<char>& std::basic_stringstream<char>::operator=(const std::basic_stringstream<char>&)’
         if (empty) buf=std::stringstream();
                       ^
In file included from render.cpp:24:0:
/usr/include/c++/4.8.5/sstream:502:11: note: ‘std::basic_stringstream<char>& std::basic_stringstream<char>::operator=(const std::basic_stringstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_stringstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.8.5/sstream:502:11: error: use of deleted function ‘std::basic_iostream<char>& std::basic_iostream<char>::operator=(const std::basic_iostream<char>&)’
In file included from /usr/include/c++/4.8.5/fstream:38:0,
                 from render.cpp:23:
/usr/include/c++/4.8.5/istream:795:11: note: ‘std::basic_iostream<char>& std::basic_iostream<char>::operator=(const std::basic_iostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_iostream
           ^
/usr/include/c++/4.8.5/istream:795:11: error: use of deleted function ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’
/usr/include/c++/4.8.5/istream:58:11: note: ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istream : virtual public basic_ios<_CharT, _Traits>
           ^

Just wondering: If buf.str().empty() then why do anything to buf to reinitialize it, which empties it anyway?

If it does need to be cleared to be certain, why not just buf.str("") to clear it (since buf.str() returns a const reference)? https://www.cplusplus.com/reference/sstream/istringstream/str/

**Comment by Wengier** [comment]
@joncampbell123 I used buf.swap(tmp) to solve a problem with loading the shader, but I don't quite remember what exactly it was. I looked at the following page, which suggested a few alternatives for swap including xx.str("") and xx=std::stringstream(), and a user mentioned that "std::stringstream(); should be the most reliable way regardless of the compiler". But unfortunately it still did not work for GCC 4.8.5 as you said. I think I will use "xx.clear(); xx.str("");" instead then because another user mentions that it will solve the  stringstream stuck issue with just xx.str(""):

https://stackoverflow.com/questions/20731/how-do-you-clear-a-stringstream-variable

**Comment by joncampbell123** [comment]
I'm not familiar with stringstream, what makes it get stuck?

If it's empty (because empty==true according to the test two lines up), why empty it again?

Does it just need some error bits cleared?

**Comment by Wengier** [comment]
@joncampbell123 I think I should have inserted a comment in the code so that I will remember the exact reason I added that part of code at that time. Right now I only remember that I tried to reset it to the default in such case, which did solved the problem I discovered back then, and the problem itself was kind of mysterious indeed.
